{* Generated by the theme, don't modify it manually. *}
{l s='Read more' d='Shop.Theme.Panda'}
{l s='Subcategories' d='Shop.Theme.Panda'}
{l s='No products' d='Shop.Theme.Panda'}
{l s='There are no products on the category.' d='Shop.Theme.Panda'}
{l s='Reference' d='Shop.Theme.Panda'}
{l s='Tags' d='Shop.Theme.Panda'}
{l s='More about' d='Shop.Theme.Panda'}
{l s='Toggle filters' d='Shop.Theme.Panda'}
{l s='View more' d='Shop.Theme.Panda'}
{l s='Select options' d='Shop.Theme.Panda'}
{l s='Limited time offer' d='Shop.Theme.Panda'}
{l s='Special offer' d='Shop.Theme.Panda'}
{l s='Limited special offer' d='Shop.Theme.Panda'}
{l s='Brand' d='Shop.Theme.Panda'}
{l s='Click here to see all products of this brand' d='Shop.Theme.Panda'}
{l s='View all reviews' d='Shop.Theme.Panda'}
{l s='Show all images' d='Shop.Theme.Panda'}
{l s='Grid view' d='Shop.Theme.Panda'}
{l s='List view' d='Shop.Theme.Panda'}
{l s='Menu' d='Shop.Theme.Panda'}
{l s='Our stores' d='Shop.Theme.Panda'}
{l s='New customers?' d='Shop.Theme.Panda'}
{l s='It\'s quick and easy to create an account to shop faster and save your order to account.' d='Shop.Theme.Panda'}
{l s='Registered customers' d='Shop.Theme.Panda'}
{l s='Dashboard' d='Shop.Theme.Panda'}
{l s='This site is under maintenance' d='Shop.Theme.Panda'}
{l s='!' d='Shop.Theme.Panda'}
{l s='Toggle left column' d='Shop.Theme.Panda'}
{l s='Left column' d='Shop.Theme.Panda'}
{l s='Toggle right column' d='Shop.Theme.Panda'}
{l s='Right column' d='Shop.Theme.Panda'}
{l s='Please sign in first.' d='Shop.Theme.Panda'}
{l s='Sign in' d='Shop.Theme.Panda'}
{l s='Payment methods' d='Shop.Theme.Panda'}
{l s='Load More Products' d='Shop.Theme.Panda'}
{l s='Top sellers' d='Shop.Theme.Panda'}
{l s='Method doesn\'t exist' d='Shop.Theme.Panda'}
{l s='Product comparison' d='Shop.Theme.Panda'}
{l s='Failed, product ID is empty' d='Shop.Theme.Panda'}
{l s='Removed from %1%compare list%2%' d='Shop.Theme.Panda'}
{l s='Emptyed %1%compare list%2%' d='Shop.Theme.Panda'}
{l s='Added to %1%compare list%2%' d='Shop.Theme.Panda'}
{l s='Remove All' d='Shop.Theme.Panda'}
{l s='Remove' d='Shop.Theme.Panda'}
{l s='Name' d='Shop.Theme.Panda'}
{l s='Price' d='Shop.Theme.Panda'}
{l s='Rating' d='Shop.Theme.Panda'}
{l s='Short description' d='Shop.Theme.Panda'}
{l s='Stock' d='Shop.Theme.Panda'}
{l s='Color' d='Shop.Theme.Panda'}
{l s='No features to compare' d='Shop.Theme.Panda'}
{l s='There are no products selected for comparison.' d='Shop.Theme.Panda'}
{l s='Add to compare' d='Shop.Theme.Panda'}
{l s='Compare' d='Shop.Theme.Panda'}
{l s='Blog' d='Shop.Theme.Panda'}
{l s='(%s selected)' d='Shop.Theme.Panda'}
{l s='Group: %s' d='Shop.Theme.Panda'}
{l s='Posted on' d='Shop.Theme.Panda'}
{l s='Just now' d='Shop.Theme.Panda'}
{l s='Year' d='Shop.Theme.Panda'}
{l s='Years' d='Shop.Theme.Panda'}
{l s='Month' d='Shop.Theme.Panda'}
{l s='Months' d='Shop.Theme.Panda'}
{l s='Week' d='Shop.Theme.Panda'}
{l s='Weeks' d='Shop.Theme.Panda'}
{l s='Day' d='Shop.Theme.Panda'}
{l s='Days' d='Shop.Theme.Panda'}
{l s='Hour' d='Shop.Theme.Panda'}
{l s='Hours' d='Shop.Theme.Panda'}
{l s='Minute' d='Shop.Theme.Panda'}
{l s='Minutes' d='Shop.Theme.Panda'}
{l s='ago' d='Shop.Theme.Panda'}
{l s='by' d='Shop.Theme.Panda'}
{l s='Tag' d='Shop.Theme.Panda'}
{l s='This category is currently unavailable.' d='Shop.Theme.Panda'}
{l s='No posts' d='Shop.Theme.Panda'}
{l s='Comments' d='Shop.Theme.Panda'}
{l s='Comment' d='Shop.Theme.Panda'}
{l s='Unknown' d='Shop.Theme.Panda'}
{l s='Archive for' d='Shop.Theme.Panda'}
{l s='January' d='Shop.Theme.Panda'}
{l s='February' d='Shop.Theme.Panda'}
{l s='March' d='Shop.Theme.Panda'}
{l s='April' d='Shop.Theme.Panda'}
{l s='May' d='Shop.Theme.Panda'}
{l s='June' d='Shop.Theme.Panda'}
{l s='July' d='Shop.Theme.Panda'}
{l s='August' d='Shop.Theme.Panda'}
{l s='September' d='Shop.Theme.Panda'}
{l s='October' d='Shop.Theme.Panda'}
{l s='November' d='Shop.Theme.Panda'}
{l s='December' d='Shop.Theme.Panda'}
{l s='Blog archives' d='Shop.Theme.Panda'}
{l s='Blog categories' d='Shop.Theme.Panda'}
{l s='Invalid blog ID' d='Shop.Theme.Panda'}
{l s='Your comment is too short. Please try again' d='Shop.Theme.Panda'}
{l s='Customer name is empty' d='Shop.Theme.Panda'}
{l s='Customer email is invalid' d='Shop.Theme.Panda'}
{l s='Please login to post a comment' d='Shop.Theme.Panda'}
{l s='Blog not found' d='Shop.Theme.Panda'}
{l s='Thank you for your comment.' d='Shop.Theme.Panda'}
{l s='Your comment may be awaiting moderation before being published.' d='Shop.Theme.Panda'}
{l s='You should wait %seconds% seconds before posting a new comment.' d='Shop.Theme.Panda'}
{l s='Please refresh the page and try again' d='Shop.Theme.Panda'}
{l s='Avatar uploaded successfully' d='Shop.Theme.Panda'}
{l s='Failed to upload avatar' d='Shop.Theme.Panda'}
{l s='This image is too large to be uploaded.' d='Shop.Theme.Panda'}
{l s='Unable to upload this image, upload folder is not writable.' d='Shop.Theme.Panda'}
{l s='Avatar deleted successfully' d='Shop.Theme.Panda'}
{l s='Failed to delete avatar' d='Shop.Theme.Panda'}
{l s='My comments of blog' d='Shop.Theme.Panda'}
{l s='Blog comments: Unable to delete customer using ID.' d='Shop.Theme.Panda'}
{l s='Blog comments: No data found.' d='Shop.Theme.Panda'}
{l s='Blog comments' d='Shop.Theme.Panda'}
{l s='Avatar' d='Shop.Theme.Panda'}
{l s='Upload a new avatar(JPEG 80x80px)' d='Shop.Theme.Panda'}
{l s='Upload' d='Shop.Theme.Panda'}
{l s='Use default' d='Shop.Theme.Panda'}
{l s='My Comments' d='Shop.Theme.Panda'}
{l s='On' d='Shop.Theme.Panda'}
{l s='Reply' d='Shop.Theme.Panda'}
{l s='Latest Comments' d='Shop.Theme.Panda'}
{l s='on' d='Shop.Theme.Panda'}
{l s='No comments' d='Shop.Theme.Panda'}
{l s='Leave a Comment' d='Shop.Theme.Panda'}
{l s='Leave a Reply' d='Shop.Theme.Panda'}
{l s='Name (required)' d='Shop.Theme.Panda'}
{l s='Email' d='Shop.Theme.Panda'}
{l s='Post comment' d='Shop.Theme.Panda'}
{l s='Cancel reply' d='Shop.Theme.Panda'}
{l s='Please [1]login[/1] to post a comment.' d='Shop.Theme.Panda'}
{l s='You should wait %delay% seconds before posting a new comment.' d='Shop.Theme.Panda'}
{l s='Related products' d='Shop.Theme.Panda'}
{l s='Recent articles' d='Shop.Theme.Panda'}
{l s='Featured articles' d='Shop.Theme.Panda'}
{l s='View More' d='Shop.Theme.Panda'}
{l s='Previous article' d='Shop.Theme.Panda'}
{l s='Next article' d='Shop.Theme.Panda'}
{l s='Prev' d='Shop.Theme.Panda'}
{l s='Next' d='Shop.Theme.Panda'}
{l s='Related articles' d='Shop.Theme.Panda'}
{l s='Search' d='Shop.Theme.Panda'}
{l s='No results were found for your search' d='Shop.Theme.Panda'}
{l s='%d result has been found.' d='Shop.Theme.Panda'}
{l s='%d results have been found.' d='Shop.Theme.Panda'}
{l s='Search for' d='Shop.Theme.Panda'}
{l s='Previous' d='Shop.Theme.Panda'}
{l s='Blog search' d='Shop.Theme.Panda'}
{l s='No tags' d='Shop.Theme.Panda'}
{l s='Brands' d='Shop.Theme.Panda'}
{l s='Product Brands' d='Shop.Theme.Panda'}
{l s='No product Brands' d='Shop.Theme.Panda'}
{l s='No items' d='Shop.Theme.Panda'}
{l s='day' d='Shop.Theme.Panda'}
{l s='days' d='Shop.Theme.Panda'}
{l s='hrs' d='Shop.Theme.Panda'}
{l s='min' d='Shop.Theme.Panda'}
{l s='sec' d='Shop.Theme.Panda'}
{l s='Currency switcher' d='Shop.Theme.Panda'}
{l s='Close' d='Shop.Theme.Panda'}
{l s='Currency selector' d='Shop.Theme.Panda'}
{l s='Settings' d='Shop.Theme.Panda'}
{l s='View my customer account' d='Shop.Theme.Panda'}
{l s='My account' d='Shop.Theme.Panda'}
{l s='Log me out' d='Shop.Theme.Panda'}
{l s='Sign out' d='Shop.Theme.Panda'}
{l s='Log in to your customer account' d='Shop.Theme.Panda'}
{l s='Login' d='Shop.Theme.Panda'}
{l s='Loved items' d='Shop.Theme.Panda'}
{l s='Wishlist' d='Shop.Theme.Panda'}
{l s='Forgot your password?' d='Shop.Theme.Panda'}
{l s='Create an account' d='Shop.Theme.Panda'}
{l s='Facebook' d='Shop.Theme.Panda'}
{l s='Featured categories' d='Shop.Theme.Panda'}
{l s='No featured categories' d='Shop.Theme.Panda'}
{l s='Featureds %nl Products' sprintf=["%nl" => "<br>"] d='Shop.Theme.Panda'}
{l s='New products' d='Shop.Theme.Panda'}
{l s='Follow' d='Shop.Theme.Panda'}
{l s='Posts' d='Shop.Theme.Panda'}
{l s='Followers' d='Shop.Theme.Panda'}
{l s='Following' d='Shop.Theme.Panda'}
{l s='View in Instagram' d='Shop.Theme.Panda'}
{l s='Click to view larger' d='Shop.Theme.Panda'}
{l s='from now' d='Shop.Theme.Panda'}
{l s='any moment now' d='Shop.Theme.Panda'}
{l s='less than a minute' d='Shop.Theme.Panda'}
{l s='about a minute' d='Shop.Theme.Panda'}
{l s='minutes' d='Shop.Theme.Panda'}
{l s='about an hour' d='Shop.Theme.Panda'}
{l s='about #d hours' d='Shop.Theme.Panda'}
{l s='a day' d='Shop.Theme.Panda'}
{l s='about a month' d='Shop.Theme.Panda'}
{l s='months' d='Shop.Theme.Panda'}
{l s='about a year' d='Shop.Theme.Panda'}
{l s='years' d='Shop.Theme.Panda'}
{l s='Follow us on Instagram' d='Shop.Theme.Panda'}
{l s='Can not connect to Instagram or you do not have permissions to get media from Instagram.' d='Shop.Theme.Panda'}
{l s='No images' d='Shop.Theme.Panda'}
{l s='Load more' d='Shop.Theme.Panda'}
{l s='Language switcher' d='Shop.Theme.Panda'}
{l s='Language selector' d='Shop.Theme.Panda'}
{l s='Product deleted' d='Shop.Theme.Panda'}
{l s='Failed to delete  this product' d='Shop.Theme.Panda'}
{l s='Loved it!' d='Shop.Theme.Panda'}
{l s='Adding to love failed' d='Shop.Theme.Panda'}
{l s='My loved products' d='Shop.Theme.Panda'}
{l s='Delete' d='Shop.Theme.Panda'}
{l s='My loved articles' d='Shop.Theme.Panda'}
{l s='You haven\'t loved yet.' d='Shop.Theme.Panda'}
{l s='Love' d='Shop.Theme.Panda'}
{l s='Create a free account to save loved items.' d='Shop.Theme.Panda'}
{l s='Add to loved' d='Shop.Theme.Panda'}
{l s='View my loved products' d='Shop.Theme.Panda'}
{l s='Loved' d='Shop.Theme.Panda'}
{l s='My loved items' d='Shop.Theme.Panda'}
{l s='Loved products' d='Shop.Theme.Panda'}
{l s='Loved articles' d='Shop.Theme.Panda'}
{l s='View all' d='Shop.Theme.Panda'}
{l s='Manage my customer account' d='Shop.Theme.Panda'}
{l s='My orders' d='Shop.Theme.Panda'}
{l s='My merchandise returns' d='Shop.Theme.Panda'}
{l s='My returns' d='Shop.Theme.Panda'}
{l s='My credit slips' d='Shop.Theme.Panda'}
{l s='My addresses' d='Shop.Theme.Panda'}
{l s='My personal info' d='Shop.Theme.Panda'}
{l s='Manage my personal information' d='Shop.Theme.Panda'}
{l s='My vouchers' d='Shop.Theme.Panda'}
{l s='Specials' d='Shop.Theme.Panda'}
{l s='Contact us' d='Shop.Theme.Panda'}
{l s='Sitemap' d='Shop.Theme.Panda'}
{l s='Manufacturers' d='Shop.Theme.Panda'}
{l s='Suppliers' d='Shop.Theme.Panda'}
{l s='Categories' d='Shop.Theme.Panda'}
{l s='manage my customer account' d='Shop.Theme.Panda'}
{l s='my merchandise returns' d='Shop.Theme.Panda'}
{l s='manage my personal information' d='Shop.Theme.Panda'}
{l s='Invalid email address' d='Shop.Theme.Panda'}
{l s='Sign up for our newsletter[1][2]%conditions%[/2]' d='Shop.Theme.Panda'}
{l s='Invalid email address.' d='Shop.Theme.Panda'}
{l s='This email address is not registered.' d='Shop.Theme.Panda'}
{l s='An error occurred while attempting to unsubscribe.' d='Shop.Theme.Panda'}
{l s='Unsubscription successful.' d='Shop.Theme.Panda'}
{l s='This email address is already registered.' d='Shop.Theme.Panda'}
{l s='An error occurred during the subscription process.' d='Shop.Theme.Panda'}
{l s='A verification email has been sent. Please check your inbox.' d='Shop.Theme.Panda'}
{l s='You have successfully subscribed to this newsletter.' d='Shop.Theme.Panda'}
{l s='This email is already registered and/or invalid.' d='Shop.Theme.Panda'}
{l s='Thank you for subscribing to our newsletter.' d='Shop.Theme.Panda'}
{l s='You may unsubscribe at any moment. For that purpose, please find our contact info in the legal notice.' d='Shop.Theme.Panda'}
{l s='Newsletter subscription: Unable to delete customer using email.' d='Shop.Theme.Panda'}
{l s='Newsletter subscription: No data found.' d='Shop.Theme.Panda'}
{l s='Newsletter' d='Shop.Theme.Panda'}
{l s='Your e-mail' d='Shop.Theme.Panda'}
{l s='Subscribe' d='Shop.Theme.Panda'}
{l s='Do not show again' d='Shop.Theme.Panda'}
{l s='Title' d='Shop.Theme.Panda'}
{l s='Notification' d='Shop.Theme.Panda'}
{l s='Account' d='Shop.Theme.Panda'}
{l s='Checkout' d='Shop.Theme.Panda'}
{l s='Order confirmation' d='Shop.Theme.Panda'}
{l s='Shopping cart' d='Shop.Theme.Panda'}
{l s='Recaptcha site key and secret key required.' d='Shop.Theme.Panda'}
{l s='Recaptcha validate failed.' d='Shop.Theme.Panda'}
{l s='Invalid Product' d='Shop.Theme.Panda'}
{l s='Product not found' d='Shop.Theme.Panda'}
{l s='New comment for product' d='Shop.Theme.Panda'}
{l s='Invalid parameter' d='Shop.Theme.Panda'}
{l s='Invalid name' d='Shop.Theme.Panda'}
{l s='Thank you for your reply.' d='Shop.Theme.Panda'}
{l s='An error occurred during the image upload.' d='Shop.Theme.Panda'}
{l s='Please upload an image.' d='Shop.Theme.Panda'}
{l s='Invalid parameters' d='Shop.Theme.Panda'}
{l s='Reviews' d='Shop.Theme.Panda'}
{l s='Popularity' d='Shop.Theme.Panda'}
{l s='Most helpful' d='Shop.Theme.Panda'}
{l s='Newest' d='Shop.Theme.Panda'}
{l s='Oldest' d='Shop.Theme.Panda'}
{l s='Most commented' d='Shop.Theme.Panda'}
{l s='5 stars' d='Shop.Theme.Panda'}
{l s='4 stars' d='Shop.Theme.Panda'}
{l s='3 stars' d='Shop.Theme.Panda'}
{l s='2 stars' d='Shop.Theme.Panda'}
{l s='1 stars' d='Shop.Theme.Panda'}
{l s='Comment was deleted.' d='Shop.Theme.Panda'}
{l s='Error occurred when deleting comment.' d='Shop.Theme.Panda'}
{l s='Invalid secure key' d='Shop.Theme.Panda'}
{l s='Product comments' d='Shop.Theme.Panda'}
{l s='Are you sure report abuse ?' d='Shop.Theme.Panda'}
{l s='#left / #max Characters left.' d='Shop.Theme.Panda'}
{l s='Product comments: No data found.' d='Shop.Theme.Panda'}
{l s='Quantity' d='Shop.Theme.Panda'}
{l s='Order reference' d='Shop.Theme.Panda'}
{l s='Date' d='Shop.Theme.Panda'}
{l s='You have commented on the product.' d='Shop.Theme.Panda'}
{l s='view my comment' d='Shop.Theme.Panda'}
{l s='Describe it:' d='Shop.Theme.Panda'}
{l s='Use a comma to seperate words.' d='Shop.Theme.Panda'}
{l s='Describe this product using simple and short words.' d='Shop.Theme.Panda'}
{l s='Review(required):' d='Shop.Theme.Panda'}
{l s='Upload images:' d='Shop.Theme.Panda'}
{l s='Drop images here or click to upload.' d='Shop.Theme.Panda'}
{l s='Back to my comments' d='Shop.Theme.Panda'}
{l s='Your comment is awaiting moderation before being published.' d='Shop.Theme.Panda'}
{l s='Enter your name' d='Shop.Theme.Panda'}
{l s='Submit' d='Shop.Theme.Panda'}
{l s='Order reference:' d='Shop.Theme.Panda'}
{l s='Payment:' d='Shop.Theme.Panda'}
{l s='Date:' d='Shop.Theme.Panda'}
{l s='View my review' d='Shop.Theme.Panda'}
{l s='Write a review' d='Shop.Theme.Panda'}
{l s='Order is pending' d='Shop.Theme.Panda'}
{l s='No order items' d='Shop.Theme.Panda'}
{l s='No orders' d='Shop.Theme.Panda'}
{l s='Overall rating' d='Shop.Theme.Panda'}
{l s='Review' d='Shop.Theme.Panda'}
{l s='Someone' d='Shop.Theme.Panda'}
{l s='Click to zoom out' d='Shop.Theme.Panda'}
{l s='Report abuse' d='Shop.Theme.Panda'}
{l s='Helpful?' d='Shop.Theme.Panda'}
{l s='Yes' d='Shop.Theme.Panda'}
{l s='No' d='Shop.Theme.Panda'}
{l s='All reviews' d='Shop.Theme.Panda'}
{l s='All stars' d='Shop.Theme.Panda'}
{l s='With pictures' d='Shop.Theme.Panda'}
{l s='Sort order' d='Shop.Theme.Panda'}
{l s='Testimonial' d='Shop.Theme.Panda'}
{l s='By' d='Shop.Theme.Panda'}
{l s='To be the first to write a review' d='Shop.Theme.Panda'}
{l s='Leave a review' d='Shop.Theme.Panda'}
{l s='Custom name(required):' d='Shop.Theme.Panda'}
{l s='Previous product' d='Shop.Theme.Panda'}
{l s='Next product' d='Shop.Theme.Panda'}
{l s='QR code' d='Shop.Theme.Panda'}
{l s='Scan the QR code to open this page on your phone.' d='Shop.Theme.Panda'}
{l s='Search our catalog' d='Shop.Theme.Panda'}
{l s='More products.' d='Shop.Theme.Panda'}
{l s='Click for more products.' d='Shop.Theme.Panda'}
{l s='No produts were found.' d='Shop.Theme.Panda'}
{l s='Search here' d='Shop.Theme.Panda'}
{l s='More products »' d='Shop.Theme.Panda'}
{l s='Customers who bought this product also bought:' d='Shop.Theme.Panda'}
{l s='View' d='Shop.Theme.Panda'}
{l s='Popup shopping cart' d='Shop.Theme.Panda'}
{l s='Product successfully added to your shopping cart' d='Shop.Theme.Panda'}
{l s='Continue shopping' d='Shop.Theme.Panda'}
{l s='Proceed to checkout' d='Shop.Theme.Panda'}
{l s='Products you may like' d='Shop.Theme.Panda'}
{l s='Your shopping cart is empty.' d='Shop.Theme.Panda'}
{l s='Cart' d='Shop.Theme.Panda'}
{l s='View my shopping cart' d='Shop.Theme.Panda'}
{l s='item(s)' d='Shop.Theme.Panda'}
{l s='-' d='Shop.Theme.Panda'}
{l s='Recently Viewed' d='Shop.Theme.Panda'}
{l s='Viewed' d='Shop.Theme.Panda'}
{l s='Top' d='Shop.Theme.Panda'}
{l s='Share' d='Shop.Theme.Panda'}
{l s='Compare Products' d='Shop.Theme.Panda'}
{l s='Back to top' d='Shop.Theme.Panda'}
{l s='Language' d='Shop.Theme.Panda'}
{l s='Currency' d='Shop.Theme.Panda'}
{l s='Share on social networks' d='Shop.Theme.Panda'}
{l s='Popular tags' d='Shop.Theme.Panda'}
{l s='%curr% of %total%' d='Shop.Theme.Panda'}
{l s='All products of this manufacturer' d='Shop.Theme.Panda'}
{l s='Wishlists' d='Shop.Theme.Panda'}
{l s='The product was successfully added to your wishlist.' d='Shop.Theme.Panda'}
{l s='Add to %s' d='Shop.Theme.Panda'}
{l s='My wishlists' d='Shop.Theme.Panda'}
{l s='Open video' d='Shop.Theme.Panda'}
{l s='View video' d='Shop.Theme.Panda'}
{l s='You must specify a name.' d='Shop.Theme.Panda'}
{l s='This name is already used by another list.' d='Shop.Theme.Panda'}
{l s='Cannot delete this wishlist' d='Shop.Theme.Panda'}
{l s='Product added to wishlist.' d='Shop.Theme.Panda'}
{l s='Error occurred when adding products.' d='Shop.Theme.Panda'}
{l s='Failed to delete this product' d='Shop.Theme.Panda'}
{l s='This name is already used by another list' d='Shop.Theme.Panda'}
{l s='Wishlist created' d='Shop.Theme.Panda'}
{l s='Create wishilist failed' d='Shop.Theme.Panda'}
{l s='Quantity updated' d='Shop.Theme.Panda'}
{l s='Update quantity failed' d='Shop.Theme.Panda'}
{l s='Email Address is not correct:' d='Shop.Theme.Panda'}
{l s='This wishlist does not exist' d='Shop.Theme.Panda'}
{l s='An error occurred when sending this wishlist.' d='Shop.Theme.Panda'}
{l s='An error occurred:' d='Shop.Theme.Panda'}
{l s='This wishlist was sent.' d='Shop.Theme.Panda'}
{l s='Create a wishlist' d='Shop.Theme.Panda'}
{l s='Create' d='Shop.Theme.Panda'}
{l s='Delete wishlist' d='Shop.Theme.Panda'}
{l s='Copy link' d='Shop.Theme.Panda'}
{l s='Share with a friend' d='Shop.Theme.Panda'}
{l s='Email address' d='Shop.Theme.Panda'}
{l s='Send' d='Shop.Theme.Panda'}
{l s='Save' d='Shop.Theme.Panda'}
{l s='Back to wishlists' d='Shop.Theme.Panda'}
{l s='No products.' d='Shop.Theme.Panda'}
{l s='Add to wishlist' d='Shop.Theme.Panda'}
{l s='Create a free account to use wishlists.' d='Shop.Theme.Panda'}
{l s='View my wishlists' d='Shop.Theme.Panda'}
{l s='Save to wishlist' d='Shop.Theme.Panda'}
{l s='year ago' d='Shop.Theme.Panda'}
{l s='years ago' d='Shop.Theme.Panda'}
{l s='month ago' d='Shop.Theme.Panda'}
{l s='months ago' d='Shop.Theme.Panda'}
{l s='week ago' d='Shop.Theme.Panda'}
{l s='weeks ago' d='Shop.Theme.Panda'}
{l s='day ago' d='Shop.Theme.Panda'}
{l s='days ago' d='Shop.Theme.Panda'}
{l s='hour ago' d='Shop.Theme.Panda'}
{l s='hours ago' d='Shop.Theme.Panda'}
{l s='minute ago' d='Shop.Theme.Panda'}
{l s='minutes ago' d='Shop.Theme.Panda'}
{l s='second ago' d='Shop.Theme.Panda'}
{l s='seconds ago' d='Shop.Theme.Panda'}
{l s='Don\'t show out-of-stock products' d='Shop.Theme.Panda'}
{l s='Show all products.' d='Shop.Theme.Panda'}
{l s='Hide out-of-stock products.' d='Shop.Theme.Panda'}
{l s='Hide products if their default combinations are out-of-stock.' d='Shop.Theme.Panda'}
{l s='Play' d='Shop.Theme.Panda'}
{l s='You may also like' d='Shop.Theme.Panda'}