/**
 * TNT OFFICIAL MODULE FOR PRESTASHOP.
 *
 * @author    Inetum <inetum.world>
 * @copyright 2016-2021 Inetum, 2016-2021 TNT
 * @license   https://opensource.org/licenses/MIT MIT License
 */

/**
 * @author douglascrockford/JSON-js [https://github.com/douglascrockford/JSON-js/blob/master/json2.js] 2016-10-28
 * @license Public Domain. NO WARRANTY EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.
 * JSON.parse(), JSON.stringify() cross-browser.
 */
"object"!==typeof JSON&&(JSON={});
(function(){function m(a){return 10>a?"0"+a:a}function q(){return this.valueOf()}function r(a){t.lastIndex=0;return t.test(a)?'"'+a.replace(t,function(a){var c=w[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function n(a,k){var c,d=e,b=k[a];b&&"object"===typeof b&&"function"===typeof b.toJSON&&(b=b.toJSON(a));"function"===typeof h&&(b=h.call(k,a,b));switch(typeof b){case "string":return r(b);case "number":return isFinite(b)?String(b):"null";case "boolean":case "null":return String(b);
 case "object":if(!b)return"null";e+=p;var g=[];if("[object Array]"===Object.prototype.toString.apply(b)){var u=b.length;for(c=0;c<u;c+=1)g[c]=n(c,b)||"null";var f=0===g.length?"[]":e?"[\n"+e+g.join(",\n"+e)+"\n"+d+"]":"["+g.join(",")+"]";e=d;return f}if(h&&"object"===typeof h)for(u=h.length,c=0;c<u;c+=1){if("string"===typeof h[c]){var l=h[c];(f=n(l,b))&&g.push(r(l)+(e?": ":":")+f)}}else for(l in b)Object.prototype.hasOwnProperty.call(b,l)&&(f=n(l,b))&&g.push(r(l)+(e?": ":":")+f);f=0===g.length?"{}":
     e?"{\n"+e+g.join(",\n"+e)+"\n"+d+"}":"{"+g.join(",")+"}";e=d;return f}}var x=/^[\],:{}\s]*$/,y=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,z=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,A=/(?:^|:|,)(?:\s*\[)+/g,t=/[\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,v=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;"function"!==typeof Date.prototype.toJSON&&
(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+m(this.getUTCMonth()+1)+"-"+m(this.getUTCDate())+"T"+m(this.getUTCHours())+":"+m(this.getUTCMinutes())+":"+m(this.getUTCSeconds())+"Z":null},Boolean.prototype.toJSON=q,Number.prototype.toJSON=q,String.prototype.toJSON=q);var e,p,h;if("function"!==typeof JSON.stringify){var w={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};JSON.stringify=function(a,k,c){var d;p=e="";if("number"===
    typeof c)for(d=0;d<c;d+=1)p+=" ";else"string"===typeof c&&(p=c);if((h=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("JSON.stringify");return n("",{"":a})}}"function"!==typeof JSON.parse&&(JSON.parse=function(a,e){function c(b,a){var d,f=b[a];if(f&&"object"===typeof f)for(d in f)if(Object.prototype.hasOwnProperty.call(f,d)){var g=c(f,d);void 0!==g?f[d]=g:delete f[d]}return e.call(b,a,f)}a=String(a);v.lastIndex=0;v.test(a)&&(a=a.replace(v,function(a){return"\\u"+
    ("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(x.test(a.replace(y,"@").replace(z,"]").replace(A,""))){var d=eval("("+a+")");return"function"===typeof e?c({"":d},""):d}throw new SyntaxError("JSON.parse");})})();

/**
 * @author William Taverne
 * @license MIT License
 * UTF8 encode/decode, base64 encode/decode.
 */
function TNTOfficiel_UTF8Encode(d){for(var a,e=-1,f=d.length,b=[],c=0;++e<f;)128>(a=d.charCodeAt(e))?b[c]=a:2048>a?(b[c]=192|a>>6&31,b[++c]=128|a&63):65536>a?(b[c]=224|a>>12&15,b[++c]=128|a>>6&63,b[++c]=128|a&63):2097152>a&&(b[c]=240|a>>18&7,b[++c]=128|a>>12&63,b[++c]=128|a>>6&63,b[++c]=128|a&63),++c;return String.fromCharCode.apply(d,b)}
function TNTOfficiel_UTF8Decode(d){for(var a,e=-1,f=d.length,b=[],c=0;++e<f;)128>(a=d.charCodeAt(e))?b[c++]=a:191<a&&224>a?b[c++]=(a&31)<<6|d.charCodeAt(++e)&63:b[c++]=(a&15)<<12|(d.charCodeAt(++e)&63)<<6|d.charCodeAt(++e)&63;return String.fromCharCode.apply(d,b)}
function TNTOfficiel_base64Encode(d){for(var a=-3,e,f=(d),b=f.length,c="",g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split("");(a+=3)<b;)for(d=f.charCodeAt(a)<<16|(a+1<b?f.charCodeAt(a+1)<<8:0)|(a+2<b?f.charCodeAt(a+2):0),e=-1;4>++e;)c+=(a<<2)+3*e>b<<2?"=":g[d>>>6*(3-e)&63];return c}
function TNTOfficiel_base64Decode(d){for(var a,e,f=-4,b,c=d.length,g=[],h=-1,k={A:0,B:1,C:2,D:3,E:4,F:5,G:6,H:7,I:8,J:9,K:10,L:11,M:12,N:13,O:14,P:15,Q:16,R:17,S:18,T:19,U:20,V:21,W:22,X:23,Y:24,Z:25,a:26,b:27,c:28,d:29,e:30,f:31,g:32,h:33,i:34,j:35,k:36,l:37,m:38,n:39,o:40,p:41,q:42,r:43,s:44,t:45,u:46,v:47,w:48,x:49,y:50,z:51,0:52,1:53,2:54,3:55,4:56,5:57,6:58,7:59,8:60,9:61,"+":62,"/":63};(f+=4)<c;){b=-1;for(a=0;4>++b;){e=d.charAt(f+b);if("="===e)break;a|=k[e]<<6*(3-b)}g[++h]=a>>>16&255;g[++h]=a>>>8&255;
g[++h]=a>>>0&255;if("="===e)break}return (String.fromCharCode.apply(d,g))};

/**
 * @license zlib.js 2012 - imaya [https://github.com/imaya/zlib.js]
 * @license MIT License
 */
(function(){function I(d,b){var a=d.split("."),e=N;a[0]in e||!e.execScript||e.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)a.length||void 0===b?e=e[c]?e[c]:e[c]={}:e[c]=b}function A(d,b){this.index="number"===typeof b?b:0;this.d=0;this.buffer=d instanceof(m?Uint8Array:Array)?d:new (m?Uint8Array:Array)(32768);if(2*this.buffer.length<=this.index)throw Error("invalid index");this.buffer.length<=this.index&&D(this)}function D(d){var b=d.buffer,a,e=b.length,c=new (m?Uint8Array:Array)(e<<
1);if(m)c.set(b);else for(a=0;a<e;++a)c[a]=b[a];return d.buffer=c}function u(d){this.buffer=new (m?Uint16Array:Array)(2*d);this.length=0}function F(d,b){this.e=J;this.f=0;this.input=m&&d instanceof Array?new Uint8Array(d):d;this.c=0;b&&(b.lazy&&(this.f=b.lazy),"number"===typeof b.compressionType&&(this.e=b.compressionType),b.outputBuffer&&(this.b=m&&b.outputBuffer instanceof Array?new Uint8Array(b.outputBuffer):b.outputBuffer),"number"===typeof b.outputIndex&&(this.c=b.outputIndex));this.b||(this.b=
new (m?Uint8Array:Array)(32768))}function P(d,b){this.length=d;this.g=b}function r(d,b){function a(c,b){var a=c.g,d=[],e=0;var h=g[c.length];d[e++]=h&65535;d[e++]=h>>16&255;d[e++]=h>>24;switch(!0){case 1===a:a=[0,a-1,0];break;case 2===a:a=[1,a-2,0];break;case 3===a:a=[2,a-3,0];break;case 4===a:a=[3,a-4,0];break;case 6>=a:a=[4,a-5,1];break;case 8>=a:a=[5,a-7,1];break;case 12>=a:a=[6,a-9,2];break;case 16>=a:a=[7,a-13,2];break;case 24>=a:a=[8,a-17,3];break;case 32>=a:a=[9,a-25,3];break;case 48>=a:a=
[10,a-33,4];break;case 64>=a:a=[11,a-49,4];break;case 96>=a:a=[12,a-65,5];break;case 128>=a:a=[13,a-97,5];break;case 192>=a:a=[14,a-129,6];break;case 256>=a:a=[15,a-193,6];break;case 384>=a:a=[16,a-257,7];break;case 512>=a:a=[17,a-385,7];break;case 768>=a:a=[18,a-513,8];break;case 1024>=a:a=[19,a-769,8];break;case 1536>=a:a=[20,a-1025,9];break;case 2048>=a:a=[21,a-1537,9];break;case 3072>=a:a=[22,a-2049,10];break;case 4096>=a:a=[23,a-3073,10];break;case 6144>=a:a=[24,a-4097,11];break;case 8192>=a:a=
[25,a-6145,11];break;case 12288>=a:a=[26,a-8193,12];break;case 16384>=a:a=[27,a-12289,12];break;case 24576>=a:a=[28,a-16385,13];break;case 32768>=a:a=[29,a-24577,13];break;default:throw"invalid distance";}h=a;d[e++]=h[0];d[e++]=h[1];d[e++]=h[2];e=0;for(a=d.length;e<a;++e)p[r++]=d[e];l[d[0]]++;y[d[3]]++;n=c.length+b-1;t=null}var e,c,h,f,Q={},L,t,p=m?new Uint16Array(2*b.length):[],r=0,n=0,l=new (m?Uint32Array:Array)(286),y=new (m?Uint32Array:Array)(30),q=d.f;if(!m){for(c=0;285>=c;)l[c++]=0;for(c=0;29>=
c;)y[c++]=0}l[256]=1;var x=0;for(e=b.length;x<e;++x){c=f=0;for(h=3;c<h&&x+c!==e;++c)f=f<<8|b[x+c];void 0===Q[f]&&(Q[f]=[]);c=Q[f];if(!(0<n--)){for(;0<c.length&&32768<x-c[0];)c.shift();if(x+3>=e){t&&a(t,-1);c=0;for(h=e-x;c<h;++c){var k=b[x+c];p[r++]=k;++l[k]}break}0<c.length?(L=M(b,x,c),t?t.length<L.length?(k=b[x-1],p[r++]=k,++l[k],a(L,0)):a(t,-1):L.length<q?t=L:a(L,0)):t?a(t,-1):(k=b[x],p[r++]=k,++l[k])}c.push(x)}p[r++]=256;l[256]++;d.j=l;d.i=y;return m?p.subarray(0,r):p}function M(d,b,a){var e,c=
0,h=d.length;var g=0;var f=a.length;a:for(;g<f;g++){var m=a[f-g-1];var t=3;if(3<c){for(t=c;3<t;t--)if(d[m+t-1]!==d[b+t-1])continue a;t=c}for(;258>t&&b+t<h&&d[m+t]===d[b+t];)++t;t>c&&(e=m,c=t);if(258===t)break}return new P(c,b-e)}function H(d,b){var a=d.length,e=new u(572),c=new (m?Uint8Array:Array)(a),h,g;if(!m)for(h=0;h<a;h++)c[h]=0;for(h=0;h<a;++h)0<d[h]&&e.push(h,d[h]);a=Array(e.length/2);var f=new (m?Uint32Array:Array)(e.length/2);if(1===a.length)return c[e.pop().index]=1,c;h=0;for(g=e.length/
2;h<g;++h)a[h]=e.pop(),f[h]=a[h].value;e=q(f,f.length,b);h=0;for(g=a.length;h<g;++h)c[a[h].index]=e[h];return c}function q(d,b,a){function e(a){var c=r[a][t[a]];c===b?(e(a+1),e(a+1)):--g[c];++t[a]}var c=new (m?Uint16Array:Array)(a),h=new (m?Uint8Array:Array)(a),g=new (m?Uint8Array:Array)(b),f=Array(a),r=Array(a),t=Array(a),p=(1<<a)-b,k=1<<a-1,n;c[a-1]=b;for(n=0;n<a;++n)p<k?h[n]=0:(h[n]=1,p-=k),p<<=1,c[a-2-n]=(c[a-1-n]/2|0)+b;c[0]=h[0];f[0]=Array(c[0]);r[0]=Array(c[0]);for(n=1;n<a;++n)c[n]>2*c[n-1]+
h[n]&&(c[n]=2*c[n-1]+h[n]),f[n]=Array(c[n]),r[n]=Array(c[n]);for(p=0;p<b;++p)g[p]=a;for(k=0;k<c[a-1];++k)f[a-1][k]=d[k],r[a-1][k]=k;for(p=0;p<a;++p)t[p]=0;1===h[a-1]&&(--g[0],++t[a-1]);for(n=a-2;0<=n;--n){a=p=0;var l=t[n+1];for(k=0;k<c[n];k++)a=f[n+1][l]+f[n+1][l+1],a>d[p]?(f[n][k]=a,r[n][k]=b,l+=2):(f[n][k]=d[p],r[n][k]=p,++p);t[n]=0;1===h[n]&&e(n)}return g}function K(d){var b=new (m?Uint16Array:Array)(d.length),a=[],e=[],c=0,h,g;var f=0;for(h=d.length;f<h;f++)a[d[f]]=(a[d[f]]|0)+1;f=1;for(h=16;f<=
h;f++)e[f]=c,c+=a[f]|0,c<<=1;f=0;for(h=d.length;f<h;f++)for(c=e[d[f]],e[d[f]]+=1,a=b[f]=0,g=d[f];a<g;a++)b[f]=b[f]<<1|c&1,c>>>=1;return b}var N=this,m="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==typeof Uint32Array&&"undefined"!==typeof DataView;A.prototype.a=function(d,b,a){var e=this.buffer,c=this.index,h=this.d,f=e[c];a&&1<b&&(d=8<b?(G[d&255]<<24|G[d>>>8&255]<<16|G[d>>>16&255]<<8|G[d>>>24&255])>>32-b:G[d]>>8-b);if(8>b+h)f=f<<b|d,h+=b;else for(a=0;a<b;++a)f=f<<
1|d>>b-a-1&1,8===++h&&(h=0,e[c++]=G[f],f=0,c===e.length&&(e=D(this)));e[c]=f;this.buffer=e;this.d=h;this.index=c};A.prototype.finish=function(){var d=this.buffer,b=this.index,a;0<this.d&&(d[b]<<=8-this.d,d[b]=G[d[b]],b++);m?a=d.subarray(0,b):(d.length=b,a=d);return a};var k=new (m?Uint8Array:Array)(256),w;for(w=0;256>w;++w){var z=w,v=z,O=7;for(z>>>=1;z;z>>>=1)v<<=1,v|=z&1,--O;k[w]=(v<<O&255)>>>0}var G=k;u.prototype.getParent=function(d){return 2*((d-2)/4|0)};u.prototype.push=function(d,b){var a,e=
this.buffer;var c=this.length;e[this.length++]=b;for(e[this.length++]=d;0<c;)if(a=this.getParent(c),e[c]>e[a]){var f=e[c];e[c]=e[a];e[a]=f;f=e[c+1];e[c+1]=e[a+1];e[a+1]=f;c=a}else break;return this.length};u.prototype.pop=function(){var d=this.buffer,b;var a=d[0];var e=d[1];this.length-=2;d[0]=d[this.length];d[1]=d[this.length+1];for(b=0;;){var c=2*b+2;if(c>=this.length)break;c+2<this.length&&d[c+2]>d[c]&&(c+=2);if(d[c]>d[b]){var f=d[b];d[b]=d[c];d[c]=f;f=d[b+1];d[b+1]=d[c+1];d[c+1]=f}else break;
b=c}return{index:e,value:a,length:this.length}};var J=2,E=[];for(k=0;288>k;k++)switch(!0){case 143>=k:E.push([k+48,8]);break;case 255>=k:E.push([k-144+400,9]);break;case 279>=k:E.push([k-256+0,7]);break;case 287>=k:E.push([k-280+192,8]);break;default:throw"invalid literal: "+k;}F.prototype.h=function(){var d,b=this.input;switch(this.e){case 0:var a=0;for(d=b.length;a<d;){var e=m?b.subarray(a,a+65535):b.slice(a,a+65535);a+=e.length;var c=a===d,f=this.b,g=this.c;if(m){for(f=new Uint8Array(this.b.buffer);f.length<=
g+e.length+5;)f=new Uint8Array(f.length<<1);f.set(this.b)}c=c?1:0;f[g++]=c|0;c=e.length;var k=~c+65536&65535;f[g++]=c&255;f[g++]=c>>>8&255;f[g++]=k&255;f[g++]=k>>>8&255;if(m)f.set(e,g),g+=e.length,f=f.subarray(0,g);else{c=0;for(k=e.length;c<k;++c)f[g++]=e[c];f.length=g}this.c=g;this.b=f}break;case 1:a=new A(m?new Uint8Array(this.b.buffer):this.b,this.c);a.a(1,1,!0);a.a(1,2,!0);b=r(this,b);e=0;for(f=b.length;e<f;e++)if(d=b[e],A.prototype.a.apply(a,E[d]),256<d)a.a(b[++e],b[++e],!0),a.a(b[++e],5),a.a(b[++e],
b[++e],!0);else if(256===d)break;this.b=a.finish();this.c=this.b.length;break;case J:d=new A(m?new Uint8Array(this.b.buffer):this.b,this.c);var q,t,p,z=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],n=Array(19),l;f=J;d.a(1,1,!0);d.a(f,2,!0);b=r(this,b);c=H(this.j,15);k=K(c);f=H(this.i,7);g=K(f);for(q=286;257<q&&0===c[q-1];q--);for(t=30;1<t&&0===f[t-1];t--);var y=q,v=t;var x=new (m?Uint32Array:Array)(y+v);var u=new (m?Uint32Array:Array)(316),w;var B=new (m?Uint8Array:Array)(19);for(l=p=0;l<y;l++)x[p++]=
c[l];for(l=0;l<v;l++)x[p++]=f[l];if(!m)for(l=0,v=B.length;l<v;++l)B[l]=0;l=w=0;for(v=x.length;l<v;l+=p){for(p=1;l+p<v&&x[l+p]===x[l];++p);y=p;if(0===x[l])if(3>y)for(;0<y--;)u[w++]=0,B[0]++;else for(;0<y;){var C=138>y?y:138;C>y-3&&C<y&&(C=y-3);10>=C?(u[w++]=17,u[w++]=C-3,B[17]++):(u[w++]=18,u[w++]=C-11,B[18]++);y-=C}else if(u[w++]=x[l],B[x[l]]++,y--,3>y)for(;0<y--;)u[w++]=x[l],B[x[l]]++;else for(;0<y;)C=6>y?y:6,C>y-3&&C<y&&(C=y-3),u[w++]=16,u[w++]=C-3,B[16]++,y-=C}x=m?u.subarray(0,w):u.slice(0,w);
B=H(B,7);for(l=0;19>l;l++)n[l]=B[z[l]];for(p=19;4<p&&0===n[p-1];p--);z=K(B);d.a(q-257,5,!0);d.a(t-1,5,!0);d.a(p-4,4,!0);for(l=0;l<p;l++)d.a(n[l],3,!0);l=0;for(q=x.length;l<q;l++)if(e=x[l],d.a(z[e],B[e],!0),16<=e){l++;switch(e){case 16:n=2;break;case 17:n=3;break;case 18:n=7;break;default:throw"invalid code: "+e;}d.a(x[l],n,!0)}c=[k,c];k=[g,f];e=c[0];f=c[1];g=k[0];q=k[1];c=0;for(k=b.length;c<k;++c)if(a=b[c],d.a(e[a],f[a],!0),256<a)d.a(b[++c],b[++c],!0),n=b[++c],d.a(g[n],q[n],!0),d.a(b[++c],b[++c],
!0);else if(256===a)break;this.b=d.finish();this.c=this.b.length;break;default:throw"invalid compression type";}return this.b};k=function(){function d(a){switch(!0){case 3===a:return[257,a-3,0];case 4===a:return[258,a-4,0];case 5===a:return[259,a-5,0];case 6===a:return[260,a-6,0];case 7===a:return[261,a-7,0];case 8===a:return[262,a-8,0];case 9===a:return[263,a-9,0];case 10===a:return[264,a-10,0];case 12>=a:return[265,a-11,1];case 14>=a:return[266,a-13,1];case 16>=a:return[267,a-15,1];case 18>=a:return[268,
a-17,1];case 22>=a:return[269,a-19,2];case 26>=a:return[270,a-23,2];case 30>=a:return[271,a-27,2];case 34>=a:return[272,a-31,2];case 42>=a:return[273,a-35,3];case 50>=a:return[274,a-43,3];case 58>=a:return[275,a-51,3];case 66>=a:return[276,a-59,3];case 82>=a:return[277,a-67,4];case 98>=a:return[278,a-83,4];case 114>=a:return[279,a-99,4];case 130>=a:return[280,a-115,4];case 162>=a:return[281,a-131,5];case 194>=a:return[282,a-163,5];case 226>=a:return[283,a-195,5];case 257>=a:return[284,a-227,5];case 258===
a:return[285,a-258,0];default:throw"invalid length: "+a;}}var b=[],a;for(a=3;258>=a;a++){var e=d(a);b[a]=e[2]<<24|e[1]<<16|e[0]}return b}();var g=m?new Uint32Array(k):k;I("Zlib.RawDeflate",F);I("Zlib.RawDeflate.prototype.compress",F.prototype.h);k={NONE:0,FIXED:1,DYNAMIC:J};if(Object.keys)w=Object.keys(k);else for(f in w=[],z=0,k)w[z++]=f;z=0;for(v=w.length;z<v;++z){var f=w[z];I("Zlib.RawDeflate.CompressionType."+f,k[f])}}).call(this);
(function(){function I(g,f){var d=g.split("."),b=P;d[0]in b||!b.execScript||b.execScript("var "+d[0]);for(var a;d.length&&(a=d.shift());)d.length||void 0===f?b=b[a]?b[a]:b[a]={}:b[a]=f}function A(g){var f=g.length,d=0,b=Number.POSITIVE_INFINITY,a,e,c;for(e=0;e<f;++e)g[e]>d&&(d=g[e]),g[e]<b&&(b=g[e]);var h=1<<d;var k=new (r?Uint32Array:Array)(h);var m=1;var q=0;for(a=2;m<=d;){for(e=0;e<f;++e)if(g[e]===m){var t=0;var p=q;for(c=0;c<m;++c)t=t<<1|p&1,p>>=1;p=m<<16|e;for(c=t;c<h;c+=a)k[c]=p;++q}++m;q<<=
1;a<<=1}return[k,d,b]}function D(g,f){this.g=[];this.h=32768;this.c=this.f=this.d=this.k=0;this.input=r?new Uint8Array(g):g;this.l=!1;this.i=H;this.p=!1;if(f||!(f={}))f.index&&(this.d=f.index),f.bufferSize&&(this.h=f.bufferSize),f.bufferType&&(this.i=f.bufferType),f.resize&&(this.p=f.resize);switch(this.i){case M:this.a=32768;this.b=new (r?Uint8Array:Array)(32768+this.h+258);break;case H:this.a=0;this.b=new (r?Uint8Array:Array)(this.h);this.e=this.u;this.m=this.r;this.j=this.s;break;default:throw Error("invalid inflate mode");
}}function u(g,f){for(var d=g.f,b=g.c,a=g.input,e=g.d,c=a.length;b<f;){if(e>=c)throw Error("input buffer is broken");d|=a[e++]<<b;b+=8}g.f=d>>>f;g.c=b-f;g.d=e;return d&(1<<f)-1}function F(g,f){for(var d=g.f,b=g.c,a=g.input,e=g.d,c=a.length,h=f[0],k=f[1];b<k&&!(e>=c);)d|=a[e++]<<b,b+=8;a=h[d&(1<<k)-1];c=a>>>16;if(c>b)throw Error("invalid code length: "+c);g.f=d>>c;g.c=b-c;g.d=e;return a&65535}var P=this,r="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==typeof Uint32Array&&
"undefined"!==typeof DataView,M=0,H=1;D.prototype.t=function(){for(;!this.l;){var g=u(this,3);g&1&&(this.l=!0);g>>>=1;switch(g){case 0:g=this.input;var f=this.d,d=this.b,b=this.a,a=g.length,e=d.length;this.c=this.f=0;if(f+1>=a)throw Error("invalid uncompressed block header: LEN");var c=g[f++]|g[f++]<<8;if(f+1>=a)throw Error("invalid uncompressed block header: NLEN");a=g[f++]|g[f++]<<8;if(c===~a)throw Error("invalid uncompressed block header: length verify");if(f+c>g.length)throw Error("input buffer is broken");
switch(this.i){case M:for(;b+c>d.length;){a=e-b;c-=a;if(r)d.set(g.subarray(f,f+a),b),b+=a,f+=a;else for(;a--;)d[b++]=g[f++];this.a=b;d=this.e();b=this.a}break;case H:for(;b+c>d.length;)d=this.e({o:2});break;default:throw Error("invalid inflate mode");}if(r)d.set(g.subarray(f,f+c),b),b+=c,f+=c;else for(;c--;)d[b++]=g[f++];this.d=f;this.a=b;this.b=d;break;case 1:this.j(O,G);break;case 2:g=u(this,5)+257;e=u(this,5)+1;c=u(this,4)+4;a=new (r?Uint8Array:Array)(K.length);d=f=void 0;var h;for(b=0;b<c;++b)a[K[b]]=
u(this,3);if(!r)for(b=c,c=a.length;b<c;++b)a[K[b]]=0;a=A(a);c=new (r?Uint8Array:Array)(g+e);b=0;for(h=g+e;b<h;)switch(f=F(this,a),f){case 16:for(e=3+u(this,2);e--;)c[b++]=d;break;case 17:for(e=3+u(this,3);e--;)c[b++]=0;d=0;break;case 18:for(e=11+u(this,7);e--;)c[b++]=0;d=0;break;default:d=c[b++]=f}f=r?A(c.subarray(0,g)):A(c.slice(0,g));g=r?A(c.subarray(g)):A(c.slice(g));this.j(f,g);break;default:throw Error("unknown BTYPE: "+g);}}return this.m()};var q=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,
15],K=r?new Uint16Array(q):q;q=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,258,258];var N=r?new Uint16Array(q):q;q=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,0,0];var m=r?new Uint8Array(q):q;q=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577];var k=r?new Uint16Array(q):q;q=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];var w=r?new Uint8Array(q):q;q=new (r?
Uint8Array:Array)(288);var z;var v=0;for(z=q.length;v<z;++v)q[v]=143>=v?8:255>=v?9:279>=v?7:8;var O=A(q);q=new (r?Uint8Array:Array)(30);v=0;for(z=q.length;v<z;++v)q[v]=5;var G=A(q);D.prototype.j=function(g,f){var d=this.b,b=this.a;this.n=g;for(var a=d.length-258,e,c,h;256!==(e=F(this,g));)if(256>e)b>=a&&(this.a=b,d=this.e(),b=this.a),d[b++]=e;else for(e-=257,h=N[e],0<m[e]&&(h+=u(this,m[e])),e=F(this,f),c=k[e],0<w[e]&&(c+=u(this,w[e])),b>=a&&(this.a=b,d=this.e(),b=this.a);h--;)d[b]=d[b++-c];for(;8<=
this.c;)this.c-=8,this.d--;this.a=b};D.prototype.s=function(g,f){var d=this.b,b=this.a;this.n=g;for(var a=d.length,e,c,h;256!==(e=F(this,g));)if(256>e)b>=a&&(d=this.e(),a=d.length),d[b++]=e;else for(e-=257,h=N[e],0<m[e]&&(h+=u(this,m[e])),e=F(this,f),c=k[e],0<w[e]&&(c+=u(this,w[e])),b+h>a&&(d=this.e(),a=d.length);h--;)d[b]=d[b++-c];for(;8<=this.c;)this.c-=8,this.d--;this.a=b};D.prototype.e=function(){var g=new (r?Uint8Array:Array)(this.a-32768),f=this.a-32768,d,b=this.b;if(r)g.set(b.subarray(32768,
g.length));else{var a=0;for(d=g.length;a<d;++a)g[a]=b[a+32768]}this.g.push(g);this.k+=g.length;if(r)b.set(b.subarray(f,f+32768));else for(a=0;32768>a;++a)b[a]=b[f+a];this.a=32768;return b};D.prototype.u=function(g){var f,d=this.input.length/this.d+1|0,b,a,e,c=this.input,h=this.b;g&&("number"===typeof g.o&&(d=g.o),"number"===typeof g.q&&(d+=g.q));2>d?(b=(c.length-this.d)/this.n[2],e=b/2*258|0,a=e<h.length?h.length+e:h.length<<1):a=h.length*d;r?(f=new Uint8Array(a),f.set(h)):f=h;return this.b=f};D.prototype.m=
function(){var g=0,f=this.b,d=this.g,b=new (r?Uint8Array:Array)(this.k+(this.a-32768)),a,e;if(0===d.length)return r?this.b.subarray(32768,this.a):this.b.slice(32768,this.a);var c=0;for(a=d.length;c<a;++c){var h=d[c];var k=0;for(e=h.length;k<e;++k)b[g++]=h[k]}c=32768;for(a=this.a;c<a;++c)b[g++]=f[c];this.g=[];return this.buffer=b};D.prototype.r=function(){var g,f=this.a;r?this.p?(g=new Uint8Array(f),g.set(this.b.subarray(0,f))):g=this.b.subarray(0,f):(this.b.length>f&&(this.b.length=f),g=this.b);return this.buffer=
g};I("Zlib.RawInflate",D);I("Zlib.RawInflate.prototype.decompress",D.prototype.t);q={ADAPTIVE:H,BLOCK:M};var J;if(Object.keys)v=Object.keys(q);else for(E in v=[],z=0,q)v[z++]=E;z=0;for(J=v.length;z<J;++z){var E=v[z];I("Zlib.RawInflate.BufferType."+E,q[E])}}).call(this);

/** @license MIT License */
function stringToByteArray(a){a=a.split("");var c;var b=0;for(c=a.length;b<c;b++)a[b]=(a[b].charCodeAt(0)&255)>>>0;return a}
function byteArrayToString(a){return String.fromCharCode.apply({},a)};

function TNTOfficiel_inflate(a){a=stringToByteArray(TNTOfficiel_base64Decode(a));a=(new Zlib.RawInflate(a)).decompress();return TNTOfficiel_UTF8Decode(byteArrayToString(a))}
function TNTOfficiel_deflate(a){a=stringToByteArray(TNTOfficiel_UTF8Encode(a));a=(new Zlib.RawDeflate(a)).compress();return TNTOfficiel_base64Encode(byteArrayToString(a))};

/*
// Original : 250 characters.
TNTOfficiel_deflate('\n\
  _______   ____________  _________      _      __\n\
 /_  __/ | / /_  __/ __ \\/ __/ __(_)____(_)__  / /\n\
  / / /  |/ / / / / / / / /_/ /_/ / ___/ / _ \\/ /\n\
 / / / /|  / / / / /_/ / __/ __/ / /__/ /  __/ /\n\
/_/ /_/ |_/ /_/  \\____/_/ /_/ /_/\\___/_/\\___/_/\n\
');

// Deflate : 120 characters.
TNTOfficiel_inflate('TY67DQAxCEN7pnB5V7FQJBZh+NiQv+BhBUMMiD441ZJPqbMRBq9XR8JPzbahrPjil68A9XALMy+y+Vw6KrSvoDl0rOfc1tvWIV1oZXtQLmLoD2d8uPSFTQ==');
*/